### ISSUE TITLE
A very small possible bug on Natural log checkbox in column selection dialog

### ISSUE THREAD

**Issue by roentgenium** [bruceravel/demeter#22]
When I import a file obtained in transmission mode after importing some files without "natural log", the check box of natural log is not checked even though the math expression in mu(E) looks fine.

![naturallogissue](https://cloud.githubusercontent.com/assets/6039289/8844664/a144e8b2-3152-11e5-85b9-7bebb79a0a09.png)

Procedure
1. Import a data file obtained in fluorescence mode without checking the "Natural log" checkbox. Looks fine.
2. Import another data file obtained in transmission mode and just click OK. ("Natural log" is NOT checked as shown above, even though the suggest function in the plugin, PFBL12C.pm, works fine.) Looks fine.
3. Import the other data file obtained in transmission mode and just click OK. ("Natural log" is CHECKED.) Looks fine.

Environment
Windows 7 64 bit
Demeter 0.9.21
PFBL12C.pm

Thanks in advance.

**Comment by bruceravel** [comment]
@roentgenium: thanks!  good eye!

I think I now have the logic correct for setting the ln checkbutton at a996717affa04a4f16e874a5ee4e9dbfeced038d.  If you want to test it immediately (i.e. before I build a new Windows installer), grab https://raw.githubusercontent.com/bruceravel/demeter/master/lib/Demeter/UI/Athena/IO.pm and overwrite 

       C:\strawberry\perl\site\lib\Demeter\UI\Athena\IO.pm

then fire up Athena and run through your recipe.

Thanks for the clear, well-written, easily understood bug report.
B

**Comment by roentgenium** [comment]
Thanks! It works well!
