### ISSUE TITLE
Some strange figures when plotting in quad mode and k space

### ISSUE THREAD

**Issue by roentgenium** [bruceravel/demeter#25]
I am suffering of a tiny and strange figures when plotting XAS data in quad mode or k space.

My environment is
OS: Windows 7 64 bit
Athena: 0.9.24 (both of 32 bit and 64 bit)

For example, when I import a Ni foil XAS data file, the gnuplot automatically plots a graph like below.

![gnuplot_quad](https://cloud.githubusercontent.com/assets/6039289/11322896/9ff19ad6-9143-11e5-81a7-286c2f97b35e.png)

And, when I click the "k" button, the gnuplot shows the EXAFS oscillation with some garbage.
 
![gnuplot_exafs](https://cloud.githubusercontent.com/assets/6039289/11322899/a76ff460-9143-11e5-9f16-c8fdaf9e485a.png)

I tried to reinstall Demeter package both of 32 bit and 64 bit and delete the "demeter" directory in %APPDATA%, but ends with no joy.

I guess some part of gnuplot script is the cause, but I could not find it.
At least, a data file for gnuplot in the "stash" directory, "gp_*,  looks fine.

**Comment by bruceravel** [comment]
My best guess: it's a font thing.  I am trying to use [this symbol](http://www.fileformat.info/info/unicode/char/b7/index.htm) in the math expression for the y-axis label using gnuplot's so-called enhanced syntax.  This bit of text is generated [here](https://github.com/bruceravel/demeter/blob/master/lib/Demeter/Plot/Gnuplot.pm#L179) -- or possibly at line 173.  Reading the gnuplot manual, it seems this is not reliable when using a unicode encoding, which is likely given that your computer likely wants to display Japanese text.

Possibly the simplest solution is to edit [this file](https://github.com/bruceravel/demeter/blob/master/lib/Demeter/templates/plot/gnuplot/start.tmpl) on you computer and set line 8 to 
```
set encoding iso_8859_1
```
Let me know if that works.  If not, I have some other ideas.

**Comment by roentgenium** [comment]
Yes. I am on Windows 7 Japanese edition.
I edited start.tmpl as indicated and it works!

**Comment by bruceravel** [comment]
Great!  I don't recall why I chose
```gnuplot
set encoding default
```
for that file.  Seems best to set it to `iso_8859_1`.

**Comment by bruceravel** [comment]
even better is simply not to use the middle dot in the y-axis label of plots in k.
