### ISSUE TITLE
Building on Ubuntu 15.04

### ISSUE THREAD

**Issue by ptbrowne** [bruceravel/demeter#36]
I encountered some problems while building on Ubuntu using [the official tutorial](https://bruceravel.github.io/demeter/documents/SinglePage/demeter_nonroot.html). I managed to get it working so I post my solutions here.

# Wx failed to compile from source

At the `./Build installdeps` step, `wx` would not install even the second time : 

```
Makefile:1274: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255
```

This problem is also reported [here](https://aur.archlinux.org/packages/perl-wx/?comments=all). I could not manage to build from source so I ended up using the package from Debian.

```
$ sudo apt-get install libwx-perl
```

Then `./Build installdeps` reported no more dependencies to install and I was able to `./Build`.

# `wxt` terminal not present

The default terminal was X11 but I prefer the wxt one but it was not available in gnuplot when I typed `set terminal` in gnuplot.
I had to build gnuplot from source since [Debian/Ubuntu apparently dropped support for wxt](https://groups.google.com/forum/#!topic/comp.graphics.apps.gnuplot/kfYtd2pwrW0).

To build gnuplot from source:

```
$ sudo apt-get install libwxgtk2.8-dev libgtk2.0-dev
$ wget "http://downloads.sourceforge.net/project/gnuplot/gnuplot/5.0.4/gnuplot-5.0.4.tar.gz"
$ tar xzf gnuplot-5.0.4.tar.gz
$ cd gnuplot-5.0.4
$ env "TERMLIBS="-lX11" ./configure
$ make
$ sudo make install
```

After that I was able to use the `wxt` terminal by setting it in Artemis.

`File > Edit preferences > gnuplot > terminal`. Replace "x11" by "wxt". "Apply and Save".

Thanks for the Demeter suite !

**Comment by ptbrowne** [comment]
I reopen in case you want to update the tutorial.

**Comment by bruceravel** [comment]
@ptbrowne: Thanks for all this and for keeping the issue open.  I will work on incorporating all your suggestions into the documentation.  I am really grateful for the feedback.

The Qt terminal for gnuplot is pretty good also.  Like you, I prefer the wxt terminal, but Qt is all right too.  Granted, I run kde, so I'm OK with having the Qt infrastructure on my computer....

**Comment by ptbrowne** [comment]
Thanks to you for Demter ! I did not know Qt terminal as I run stock Ubuntu with Gnome but I will check it out !

**Comment by bruceravel** [comment]
Patrick, could you take a look at http://bruceravel.github.io/demeter/documents/SinglePage/demeter_nonroot.html and let me know if I have adequately addressed all your concerns.

Thanks,B

**Comment by ptbrowne** [comment]
Looks good ! Thanks !
