### ISSUE TITLE
Flatten seems incorrect with Larch backend

### ISSUE THREAD

**Issue by newville** [bruceravel/demeter#39]
It looks like the flatten calculation is messed up with the Larch backend, as the spectra have an unusually large discontinuity at E0.     I have not investigated the template.

A few of the other Larch templates might need some attention too, especially as many of the pre_edge and autobk "details" got moved into sub-groups a while ago.

**Comment by bruceravel** [comment]
You hit the nail on the head.  d6e7d89925da325010b64ad991523199ce20463f fixes the immediate problem with plotting normalized data.  There are probably things from the autobk_details subgroup that I am failing to grab, but nothing is obvious.  I wanted to resolve this issue immediately, so....
