### ISSUE TITLE
Ctrl-M and Main Doc pointer in Athena leads to bad URL

### ISSUE THREAD

**Issue by newville** [bruceravel/demeter#43]
Doing Ctrl-M in Athena points to

   http://bruceravel.github.io/demeter/documents/Athena/index.htmlindex.html

I think the `lib/Demeter/configuration/athena.demeter_conf` and/or the `document` subroutine of 
`lib/Demeter/UI/Athena.pm` needs a fix.

**Comment by bruceravel** [comment]
Thanks for catching this.
