### ISSUE TITLE
Larch version causes error in "About Athena"

### ISSUE THREAD

**Issue by newville** [bruceravel/demeter#45]
It looks like `Get.pm` is not getting the larch version correctly (or perhaps "reliably").   I think this should probably be done by adding the larch_version string to Larch's symbol table (not a bad idea anyway) and then fetching with "get_larch_scalar()".   That's a long-term fix, requiring a new version of larch....

**Comment by bruceravel** [comment]
@newville : I sidestepped this by simply not reporting on the version number.

That said, :+1: for putting the version number in the symbol table.
