### ISSUE TITLE
The installation was failed on MacBook Pro (M1 chips) machine

### ISSUE THREAD

**Issue by yu-soong** [bruceravel/demeter#64]
The installation was failed on MacBook Pro (M1 chips) machine when running `sudo port install xorg-server demeter` with the error info: "Failed to build ifeffit: command execution failed". I checked the log file and find the error was due to the lack of ifeffit package for arm chip MacBook machines, for insrance "`ifeffit-1.2.13_7+gcc11.darwin_20.arm64.tbz2` doesn't seem to exist". There is only "*86_64.tbz2" packages for intel chips.  

You are very appreciated for solving this problem!

By the way, i can't access to the maliling list. don't know why.

**Comment by bruceravel** [comment]
I'm not going to be solving this problem.  I do not own a Mac and so have no way to make the package you are asking for. It is certainly possible to successfully compile Ifeffit on a linux machine.  I imagine it would be possible on a Mac as well, but i am not well equipped to give guidacne on that.

You might consider moving to using Larch and it's XAS Viewer on your Mac.

**Comment by yu-soong** [comment]
Ok, Thanks. I'll try Larch or Parallels in Mac.
